# .comfyenv.yaml

name: "my_first_comfyui_env"
description: "Environment for generating scenic images"
version: 1

docker:
  base_image: "akatz/comfyui-env:v0.3.9-cuda-12.6.2-runtime"

python_dependencies:
  - "torch==2.0.1"
  - "numpy==1.24.3"

custom_nodes:
  - name: "my_cool_custom_node"
    repo_url: "https://github.com/exampleuser/my_cool_custom_node"
    version: "commit:abcdef0123"

models:
  - name: "v1-5-pruned-emaonly.ckpt"
    hash: "sha256:1234567890abcdef"
    type: "checkpoint"

env_metadata:
  cuda_version: "12.6.2"
  python_version: "3.10"

workflow:
  file: "scenic_lake_workflow.json"
